id: IC7E11113
source: https://www.lotsawahouse.org
source_file: null
initial_creation_type: input
imported: '2022-05-30T22:55:49.980939'
last_modified: '2022-05-30T22:55:49.980950'
parser: null
source_metadata:
  title: Rendawa Series
  language: en
  description: 'Texts by and about Rendawa Shönnu Lodrö (red mda'' ba gzhon nu blo
    gros, 1349–1412), the famed Sakya scholar and teacher of Tsongkhapa Lobzang Drakpa:'
  volume:
    fD069:
      title: Prayer to Rendawa Shönnu Lodrö
      base_file: fD069.txt
      order: 1
      parent: Prayers
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
